export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';   
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';  
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 

export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';
export const SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION';
export const TERMINATE_NOTIFICATION = 'TERMINATE_NOTIFICATION';

export const SUCCESS_UPDATE_ANNOUNCEMENT = 'SUCCESS_UPDATE_ANNOUNCEMENT';
export const ERROR_UPDATE_ANNOUNCEMENT = 'ERROR_UPDATE_ANNOUNCEMENT';
export const SUCCESS_CREATE_ANNOUNCEMENT = 'SUCCESS_CREATE_ANNOUNCEMENT';
export const SUCCESS_ADD_MOVIE_FAVOURITES = 'SUCCESS_ADD_MOVIE_FAVOURITES';
export const SUCCESS_REMOVE_MOVIE_FAVOURITES = 'SUCCESS_REMOVE_MOVIE_FAVOURITES';